name: Cypress E2E Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths-ignore:
      - "package-lock.json"
      - "package.json"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    outputs:
      failure: ${{ steps.set-failure.outputs.status }}
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # This is where you get multiple machines. By default it's 1. Add more here if you need them
        # Please keep an eye on how many minutes you're using and use Cypress Dashboard to find the optimal number
        containers: [1]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up npm registry
        uses: bduff9/use-npmrc@v1.2
        with:
          dot-npmrc: ${{ secrets.NEXUS_GITHUB_NPMRC }}

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          start: npm run preview:e2e
          wait-on: "http://127.0.0.1:5050"
          wait-on-timeout: 180
          project: ./tests/e2e
          record: false # Once you get a Cypress Dashboard project and Key, you can set these to true
          parallel: false
          browser: chrome # Try to use a real browser such as Chrome instead of Electron
        env:
          # These are your tokens from Cypress Dashboard. Use the repo secrets
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # The github token is a personal access token. This is for the Github PR integration with Cypress Dashboard which can be set up per-project
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
